(function(){/*

SPF
(c) 2012-2016 Google Inc.
https://ajax.googleapis.com/ajax/libs/spf/2.4.0/LICENSE
*/
function k(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(b,c)}}function aa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function m(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}
var p=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};function ba(){};function ca(a){var b=document.body;b.dataset?b.dataset.spfName=a:b.setAttribute("data-"+"spfName".replace(/([A-Z])/g,"-$1").toLowerCase(),a)};function q(a,b){return t[a]=b}var t=window._spf_state||{};window._spf_state=t;function u(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function da(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function ea(a,b){if(a.some)return a.some(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&b.call(void 0,a[c],c,a))return!0;return!1}
function fa(a,b){if(a.filter)return a.filter(b,void 0);var c=[];u(a,function(a,e,f){b.call(void 0,a,e,f)&&c.push(a)});return c}function ga(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;u(a,function(a,e,f){c[e]=b.call(void 0,a,e,f)});return c}function w(a){return"[object Array]"==Object.prototype.toString.call(a)?a:[a]};var ha={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"reload-identifier":null,"request-timeout":0,"url-identifier":"?spf=__type__"},x={};"config"in t||q("config",x);x=t.config;function ia(a,b){var c=b||document;return c.querySelectorAll?c.querySelectorAll(a):[]}function ja(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}function ka(a,b,c){b=b||document;var d=b.createElement("iframe");d.id=a||"";d.src='javascript:""';d.style.display="none";c&&(d.onload=k(c,null,d));b.body.appendChild(d);return d};function la(a,b,c,d){var e=d||{},f=!1,l=0,g,h=new XMLHttpRequest;h.open(a,b,!0);h.timing={};var n=h.abort;h.abort=function(){clearTimeout(g);h.onreadystatechange=null;n.call(h)};h.onreadystatechange=function(){var a=h.timing;if(2==h.readyState){a.responseStart=a.responseStart||p();if("json"==h.responseType)f=!1;else if(-1<(h.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked"))f=!0;else{var a=h.getResponseHeader("X-Firefox-Spdy"),c=window.chrome&&chrome.loadTimes&&chrome.loadTimes(),
c=c&&c.wasFetchedViaSpdy;f=!(!a&&!c)}e.M&&e.M(h)}else 3==h.readyState?f&&e.u&&(a=h.responseText.substring(l),l=h.responseText.length,e.u(h,a)):4==h.readyState&&(a.responseEnd=a.responseEnd||p(),window.performance&&window.performance.getEntriesByName&&(h.resourceTiming=window.performance.getEntriesByName(b).pop()),f&&e.u&&h.responseText.length>l&&(a=h.responseText.substring(l),l=h.responseText.length,e.u(h,a)),clearTimeout(g),e.L&&e.L(h))};"responseType"in h&&"json"==e.responseType&&(h.responseType=
"json");e.withCredentials&&(h.withCredentials=e.withCredentials);d="FormData"in window&&c instanceof FormData;a="POST"==a&&!d;if(e.headers)for(var r in e.headers)h.setRequestHeader(r,e.headers[r]),"content-type"==r.toLowerCase()&&(a=!1);a&&h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");0<e.O&&(g=setTimeout(function(){h.abort();e.N&&e.N(h)},e.O));h.timing.fetchStart=p();h.send(c);return h};function y(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function ma(a){return"[object String]"==Object.prototype.toString.call(a)}var na=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function z(a,b){var c=a.split(b),d=1==c.length;return[c[0],d?"":b,d?"":c.slice(1).join(b)]};function oa(a){a.data&&ma(a.data)&&0==a.data.lastIndexOf("spf:",0)&&pa(a.data.substring(4))}function pa(a){var b=A[a];b&&(delete A[a],b())}function qa(a){window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)}function ra(a){window.removeEventListener?window.removeEventListener("message",a,!1):window.detachEvent&&window.detachEvent("onmessage",a)}
var sa=function(){function a(){b=!1}if(!window.postMessage)return!1;var b=!0;qa(a);window.postMessage("","*");ra(a);return b}(),A={};"async-defers"in t||q("async-defers",A);A=t["async-defers"];sa&&("async-listener"in t&&ra(t["async-listener"]),qa(oa),q("async-listener",oa));function ta(a){var b=B();a in b&&delete b[a]}function ua(){var a=B(),b;for(b in a)va(a[b])||delete a[b];a=B();b=parseInt(x["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(0>=b))for(var c=0;c<b;c++){var d=Infinity,e,f;for(f in a)a[f].count<d&&(e=f,d=a[f].count);delete a[e]}}function va(a){if(!(a&&"data"in a))return!1;var b=a.life,b=isNaN(b)?Infinity:b;a=a.time;return p()-a<b}function wa(a){var b=parseInt(t["cache-counter"],10)||0;b++;q("cache-counter",b);a.count=b}
function B(a){return!a&&"cache-storage"in t?t["cache-storage"]:q("cache-storage",a||{})};function xa(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function ya(a,b){if(b){if(a.classList)return a.classList.contains(b);var c=xa(a);return ea(c,function(a){return a==b})}return!1}function C(a,b){b&&(a.classList?a.classList.add(b):ya(a,b)||(a.className+=" "+b))}function D(a,b){if(b)if(a.classList)a.classList.remove(b);else{var c=xa(a),c=fa(c,function(a){return a!=b});a.className=c.join(" ")}};function za(a,b,c){var d=null,e=window.history.state;if(e){var d={},f;for(f in e)d[f]=e[f]}if(b)for(f in d=d||{},b)d[f]=b[f];Aa(!0,a,d,c)}function Aa(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=p();q("history-timestamp",e);c["spf-timestamp"]=e;if(a)Ba(c,b);else if(a=Ca().contentWindow.history.pushState,"function"==typeof a)a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");q("history-url",b);d&&(d=t["history-callback"])&&d(b,c)}}
function Ea(a){var b=window.location.href;if(t["history-ignore-pop"])q("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==t["history-url"]?(q("history-timestamp",c),Ba(a,b)):(a["spf-back"]=c<parseInt(t["history-timestamp"],10),a["spf-current"]=t["history-url"],q("history-timestamp",c),q("history-url",b),(c=t["history-callback"])&&c(b,a))}}
function Ba(a,b){var c=Ca().contentWindow.history.replaceState;if("function"==typeof c)c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function Ca(){var a=document.getElementById("history-iframe");a||(a=ka("history-iframe"));return a};function Fa(a,b){a&&b&&(a in E||(E[a]=[]),E[a].push(b))}function Ha(a,b){a in E&&b&&da(E[a],function(a,d,e){return a==b?(e[d]=null,!1):!0})}function Ia(a){a in E&&u(E[a],function(a,c,d){d[c]=null;a&&a()})}var E={};"ps-s"in t||q("ps-s",E);E=t["ps-s"];function G(a,b,c){var d=H[a];return a&&b?(d||(d=H[a]={items:[],o:0,m:0,A:1}),d.items.push({D:b,B:c||0})):d&&d.items.length||0}function I(a,b){var c=H[a];if(c){var d=!!c.o||!!c.m;0<c.A&&(b||!d)&&Ja(a,b)}}function J(a){(a=H[a])&&a.A--}function K(a,b){var c=H[a];c&&(c.A++,I(a,b))}function Ka(a){var b=H[a];b&&(La(b),delete H[a])}
function Ja(a,b){var c=H[a];if(c&&(La(c),0<c.A&&c.items.length)){var d=c.items[0];if(d){var e=k(function(a,b){b();a()},null,k(Ja,null,a,b));b?(c.items.shift(),e(d.D)):Ma(c,d,e)}}}function Ma(a,b,c){b.B?(c=k(c,null,ba),a.m=setTimeout(c,b.B),b.B=0):(a.items.shift(),c=k(c,null,b.D),(b=(b=x["advanced-task-scheduler"])&&b.addTask)?a.o=b(c):a.m=setTimeout(c,0))}function La(a){if(a.o){var b=x["advanced-task-scheduler"];(b=b&&b.cancelTask)&&b(a.o);a.o=0}a.m&&(clearTimeout(a.m),a.m=0)}var H={};function L(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,username:b.username,password:b.password};a.origin=a.protocol+"//"+a.host;a.pathname&&"/"==a.pathname[0]||(a.pathname="/"+a.pathname);return a}function M(a,b){var c=L(a);return b?c.href:z(c.href,"#")[0]}
function Na(a,b){var c=z(a,"#");a=c[0];u(b,function(b){a=a.replace(new RegExp("([?&])"+b+"(?:=[^&]*)?(?:(?=[&])|$)","g"),function(a,b){return"?"==b?b:""})});y(a,"?")&&(a=a.slice(0,-1));return a+c[1]+c[2]}function Oa(a){var b=x["advanced-persistent-parameters"]||"",c=z(a,"#");a=c[0];var d=-1!=a.indexOf("?")?"&":"?";return a+(b?d+b:"")+c[1]+c[2]};function Pa(a,b,c,d){var e="js"==a;b=N(a,b);var f=c||"^"+b,l=O(a,f),g;c&&(g=P[O(a,c)])&&b!=g&&(m(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:c,url:g}),e=g,delete P[O(a,c)],e&&delete Q[O(a,e)],delete E[O(a,c)],Fa(l,k(Qa,null,a,c,g)));if((e=Q[O(a,b)])&&f!=e){delete P[O(a,e)];delete Q[O(a,b)];var h=O(a,e);h&&l&&h in E&&(E[l]=(E[l]||[]).concat(E[h]),delete E[h])}Q[O(a,b)]=f;P[O(a,f)]=b;Fa(l,d);d=k(Ra,null,a);R[O(a,b,void 0)]?(e&&f!=e&&(a=Sa(a,b))&&a.setAttribute("name",c||""),d()):(a=Ta(a,b,d,void 0,
void 0,g))&&c&&a.setAttribute("name",c)}function Ua(a,b){var c=P[O(a,b)];delete P[O(a,b)];c&&delete Q[O(a,c)];delete E[O(a,b)];Qa(a,b,c)}function Qa(a,b,c){c&&(m("js"==a?"spfjsunload":"spfcssunload",{name:b,url:c}),Va(a,c))}function Ra(a){var b=O(a,""),c;for(c in E)0==c.indexOf(b)&&da(c.substring(b.length).split("|"),k(Wa,null,a))&&Ia(c)}
function Ta(a,b,c,d,e,f){function l(){R[O(a,b,e)]&&(R[O(a,b,e)]=2);g&&n&&n.parentNode&&h==document&&n.parentNode.removeChild(n);c&&setTimeout(c,0);return null}var g="js"==a;b=N(a,b);R[O(a,b,e)]=1;var h=d||document,n=h.createElement(g?"script":"link");if(!b)return l();d=S(b);n.className=O(a,d);"onload"in n?n.onerror=n.onload=l:n.onreadystatechange=function(){/^c|loade/.test(n.readyState)&&l()};d=h.getElementsByTagName("head")[0]||h.body;g?(n.async=!0,n.src=b,d.insertBefore(n,d.firstChild)):(n.rel=
"stylesheet",n.href=b,(f=f?Sa(a,f,d):null)?d.insertBefore(n,f):d.appendChild(n));return n}function Va(a,b){b=N(a,b);var c=Sa(a,b,void 0);c&&c.parentNode&&c.parentNode.removeChild(c);delete R[O(a,b)]}function Sa(a,b,c){b=S(b);return ia("."+O(a,b),c)[0]}
function Xa(a){var b="js"==a,c=[];u(ia(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href,e=N(a,e);if(!R[O(a,e,void 0)]){R[O(a,e,void 0)]=2;var f=S(e);C(d,O(a,f));if(f=d.getAttribute("name"))Q[O(a,e)]=f,P[O(a,f)]=e;c.push(d)}})}
function Ya(a,b,c){if(b&&(b=N(a,b),c||!R[O(a,b,void 0)]))if(c&&"img"==a)Za(b);else{var d=S(b),e=O(a,d),f=O(a,"prefetch"),d=document.getElementById(f);if(!d)d=ka(f,null,function(a){a.title=f;I(f,!0)});else if(!c&&d.contentWindow.document.getElementById(e))return;a=k($a,null,d,a,b,e,f);d.title?a():G(f,a)}}
function $a(a,b,c,d,e){var f="js"==b,l="css"==b;a=a.contentWindow.document;var g=a.getElementById(d);g&&g.parentNode.removeChild(g);f?(g=a.createElement("object"),ab?a.createElement("script").src=c:g.data=c,g.id=d,a.body.appendChild(g)):l?(g=Ta(b,c,null,a,e),g.id=d):(g=a.createElement("img"),ab&&(c=c+"#"+p()),g.src=c,g.id=d,a.body.appendChild(g))}function Za(a){var b=new Image;ab&&(a=a+"#"+p());b.src=a}
function bb(a,b,c){for(var d="js"==a,e=P[O(a,c)],f=b.replace(/\s/g,""),f=f||"",l=0,g=0,h=f.length;g<h;++g)l=31*l+f.charCodeAt(g),l%=4294967296;f="hash-"+l;P[O(a,c)]=f;!cb(a,f)&&(b=db(a,b))&&(R[O(a,f,void 0)]=2,b&&!d&&(d=S(f),b.className=O(a,d),b.setAttribute("name",c)),(e=e&&e[0])&&Va(a,e))}
function db(a,b){b=na(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body,d;"js"==a?(d=document.createElement("script"),d.text=b,c.appendChild(d),c.removeChild(d)):(d=document.createElement("style"),c.appendChild(d),"styleSheet"in d?d.styleSheet.cssText=b:d.appendChild(document.createTextNode(b)));return d}
function N(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(0>d){if(0==b.lastIndexOf("hash-",0))return b;c=t[c]||"";if(ma(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);"img"!=a&&(b=0>b.indexOf("."+a)?b+"."+a:b);b=M(b)}else 0==d&&(b=M(b))}return b}function O(a,b,c){return a+"-"+b+(c?"-"+c:"")}function S(a){return a?String(a).replace(/[^\w]/g,""):""}function cb(a,b){var c=R[O(a,b,void 0)];return""==b||2==c}function Wa(a,b){var c=P[O(a,b)];return void 0!=c&&cb(a,c)}
var R={},Q={},P={},ab=-1!=navigator.userAgent.indexOf(" Trident/");"rsrc-s"in t||q("rsrc-s",R);R=t["rsrc-s"];"rsrc-n"in t||q("rsrc-n",Q);Q=t["rsrc-n"];"rsrc-u"in t||q("rsrc-u",P);P=t["rsrc-u"];function eb(a){a=w(a);u(a,function(a){Ya("img",a,!0)})};function fb(a,b,c){Pa("js",a,b,c)}function gb(a){Ua("js",a)}function hb(a,b){Ta("js",a,b)}function ib(a){a=w(a);u(a,function(a){Ya("js",a)})}function jb(a,b,c){a=w(a);a=fa(a,function(a){return!!a});var d=[];u(a,function(a){void 0==P[O("js",a)]&&d.push(a)});var e=!d.length;if(b){var f=da(a,k(Wa,null,"js"));e&&f?b():(a=O("js",a.sort().join("|")),Fa(a,b))}c&&!e&&c(d)}function kb(a,b){a=w(a);u(a,function(a){if(a){var b=T[a]||a,b=N("js",b),c=P[O("js",a)];c&&b!=c&&lb(a)}});jb(a,b,mb)}
function mb(a){u(a,function(a){function b(){fb(e,a)}var d=U[a],e=T[a]||a;d?kb(d,b):b()})}function lb(a){a=w(a);u(a,function(a){var b=[],d;for(d in U){var e=U[d],e=w(e);u(e,function(c){c==a&&b.push(d)})}u(b,function(a){lb(a)});gb(a)})}function nb(a,b){bb("js",a,b)}function ob(a){db("js",a)}var U={};"js-d"in t||q("js-d",U);var U=t["js-d"],T={};"js-u"in t||q("js-u",T);T=t["js-u"];function pb(a,b,c){Pa("css",a,b,c)}function qb(a,b){Ta("css",a,b)}function rb(a){a=w(a);u(a,function(a){Ya("css",a)})};function sb(a,b,c){if(b){b=[];var d,e=0;c&&(a+="\r\n");var f=a.indexOf("[\r\n",e);for(-1<f&&(e=f+3);-1<(f=a.indexOf(",\r\n",e));)d=na(a.substring(e,f)),e=f+3,d&&b.push(JSON.parse(d));f=a.indexOf("]\r\n",e);-1<f&&(d=na(a.substring(e,f)),e=f+3,d&&b.push(JSON.parse(d)));d="";a.length>e&&(d=a.substring(e),c&&y(d,"\r\n")&&(d=d.substring(0,d.length-2)));b=tb(b);return{w:b,g:d}}a=JSON.parse(a);b=tb(w(a));return{w:b,g:""}}
function V(a,b,c,d){var e=c&&0==c.type.lastIndexOf("navigate",0),f=c&&c.reverse,l=c&&!!c.position,g=c&&c.j,h=b.name||"",n="process "+M(a),r=!x["experimental-process-async"],v;v=0;b.timing||(b.timing={});b.title&&(document.title=b.title);e&&b.url&&M(b.url)!=M(window.location.href)&&za(b.url+window.location.hash);b.head&&(v=k(function(a,b){var c=W(a);ub(c);vb(c);J(n);wb(c,function(){b.spfProcessHead=p();K(n,r)})},null,b.head,b.timing),v=G(n,v));b.attr&&(v=k(function(a,b){for(var c in a){var d=document.getElementById(c);
if(d){var e=a[c],f=void 0;for(f in e){var g=e[f];"class"==f?d.className=g:"style"==f?d.style.cssText=g:(d.setAttribute(f,g),"value"==f&&(d[f]=g))}}}b.spfProcessAttr=p()},null,b.attr,b.timing),v=G(n,v));var F=b.body||{},vc=v,Ga;for(Ga in F)v=k(function(a,b){var d=document.getElementById(a);if(d){!e||l||g||(q("nav-scroll-position",null),q("nav-scroll-url",null),window.scroll(0,0),g=!0,c&&(c.j=!0));var v=W(b);vb(v);var Da=function(){J(n);wb(v,function(){K(n,r)})},F=x["animation-class"];xb&&ya(d,F)?(d=
new yb(d,v.html,F,h,!!f),J(n),I(d.key,!0),G(d.key,k(zb,null,d),0),G(d.key,k(Ab,null,d),17),G(d.key,k(Bb,null,d),d.T),G(d.key,k(function(){Da();K(n,r)},null),0),I(d.key)):(F=x["experimental-html-handler"])?(J(n),F(v.html,d,function(){Da();K(n,r)})):(d.innerHTML=v.html,Da())}},null,Ga,F[Ga],b.timing),v=G(n,v);F=v-vc;b.foot?(v=k(function(a,b,c){c&&(b.spfProcessBody=p());a=W(a);vb(a);J(n);wb(a,function(){b.spfProcessFoot=p();K(n,r)})},null,b.foot,b.timing,F),v=G(n,v)):F&&(v=k(function(a){a.spfProcessBody=
p()},null,b.timing),v=G(n,v));d&&(v=G(n,k(d,null,a,b)));I(n,r)}function Cb(a,b,c,d){c="preprocess "+M(a);var e;b.head&&(e=k(function(a){a=W(a);ub(a);Db(a);Eb(a)},null,b.head),G(c,e));var f=b.body||{},l;for(l in f)f[l]&&(e=k(function(a,b){var c=W(b);Db(c);Eb(c)},null,l,f[l]),G(c,e));b.foot&&(e=k(function(a){a=W(a);Db(a);Eb(a)},null,b.foot),G(c,e));d&&G(c,k(d,null,a,b));I(c)}
function zb(a){C(a.a,a.s);C(a.a,a.H);C(a.a,a.K);C(a.a,a.I);C(a.a,a.J);a.l=document.createElement("div");a.l.className=a.S;var b=a.a,c=a.l;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.f=document.createElement("div");a.f.className=a.R;a.f.innerHTML=a.P;a.reverse?(b=a.l,b.parentNode.insertBefore(a.f,b)):(b=a.l,b.parentNode.insertBefore(a.f,b.nextSibling))}function Ab(a){D(a.a,a.I);D(a.a,a.J);C(a.a,a.F);C(a.a,a.G)}
function Bb(a){a.a.removeChild(a.l);var b=a.f,c,d=b.parentNode;if(d&&11!=d.nodeType)if(b.removeNode)b.removeNode(!1);else{for(;c=b.firstChild;)d.insertBefore(c,b);d.removeChild(b)}D(a.a,a.F);D(a.a,a.G);D(a.a,a.H);D(a.a,a.K);D(a.a,a.s)}function tb(a){u(w(a),function(a){if(a){a.head&&(a.head=W(a.head));if(a.body)for(var b in a.body)a.body[b]=W(a.body[b]);a.foot&&(a.foot=W(a.foot))}});return a}
function W(a){var b=new Fb;if(!a)return b;if(!ma(a))return a.scripts&&u(a.scripts,function(a){b.scripts.push({url:a.url||"",text:a.text||"",name:a.name||"",async:a.async||!1})}),a.styles&&u(a.styles,function(a){b.styles.push({url:a.url||"",text:a.text||"",name:a.name||""})}),a.links&&u(a.links,function(a){"spf-preconnect"==a.rel&&b.links.push({url:a.url||"",rel:a.rel||""})}),b.html=a.html||"",b;a=a.replace(Gb,function(a,d,e,f){if("script"==d){d=(d=e.match(Hb))?d[1]:"";var c=e.match(Ib),c=c?c[1]:"",
g=Jb.test(e);e=Kb.exec(e);return(e=!e||-1!=e[1].indexOf("/javascript")||-1!=e[1].indexOf("/x-javascript")||-1!=e[1].indexOf("/ecmascript"))?(b.scripts.push({url:c,text:f,name:d,async:g}),""):a}return"style"==d&&(d=(d=e.match(Hb))?d[1]:"",e=Kb.exec(e),e=!e||-1!=e[1].indexOf("text/css"))?(b.styles.push({url:"",text:f,name:d}),""):a});a=a.replace(Lb,function(a,d){var c=d.match(Mb),c=c?c[1]:"";if("stylesheet"==c){var c=(c=d.match(Hb))?c[1]:"",f=d.match(Nb),f=f?f[1]:"";b.styles.push({url:f,text:"",name:c});
return""}return"spf-preconnect"==c?(f=(f=d.match(Nb))?f[1]:"",b.links.push({url:f,rel:c}),""):a});b.html=a;return b}function wb(a,b){if(0>=a.scripts.length)b&&b();else{var c=-1,d=function(){c++;if(c<a.scripts.length){var e=a.scripts[c],f=function(){};e.url?f=e.name?k(fb,null,e.url,e.name):k(hb,null,e.url):e.text&&(f=e.name?k(nb,null,e.text,e.name):k(ob,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}
function Eb(a){0>=a.scripts.length||(a=ga(a.scripts,function(a){return a.url}),ib(a))}function vb(a){0>=a.styles.length||u(a.styles,function(a){a.url?a.name?pb(a.url,a.name):qb(a.url):a.text&&(a.name?bb("css",a.text,a.name):db("css",a.text))})}function Db(a){0>=a.styles.length||(a=ga(a.styles,function(a){return a.url}),rb(a))}function ub(a){0>=a.links.length||(a=ga(a.links,function(a){return"spf-preconnect"==a.rel?a.url:""}),eb(a))}
function yb(a,b,c,d,e){var f=parseInt(x["animation-duration"],10);this.a=a;this.P=b;this.T=f;this.reverse=e;b=document.body;b=(b.dataset?b.dataset.spfName:b.getAttribute("data-"+"spfName".replace(/([A-Z])/g,"-$1").toLowerCase()))||"";f=parseInt(t.uid,10)||0;f++;this.key=a["spf-key"]||(a["spf-key"]=""+q("uid",f));this.H=b&&c+"-from-"+b;this.K=d&&c+"-to-"+d;this.l=null;this.S=c+"-old";this.f=null;this.R=c+"-new";this.s=c+(e?"-reverse":"-forward");this.I=c+"-start";this.J=this.s+"-start";this.F=c+"-end";
this.G=this.s+"-end"}function Fb(){this.html="";this.scripts=[];this.styles=[];this.links=[]}
var xb=function(){var a=document.createElement("div");return"transition"in a.style?!0:ea(["webkit","Moz","Ms","O","Khtml"],function(b){return b+"Transition"in a.style})}(),Lb=/\x3clink([\s\S]*?)\x3e/ig,Gb=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,Jb=/(?:\s|^)async(?:\s|=|$)/i,Nb=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,Hb=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,Mb=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,Ib=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i,Kb=/(?:\s|^)type\s*=\s*["']([^"']+)["']/i;function Ob(a,b){var c=b||{};c.method=((c.method||"GET")+"").toUpperCase();c.type=c.type||"request";var d=a,e=x["url-identifier"]||"";if(e){var e=e.replace("__type__",c.type||""),f=z(d,"#"),l=z(f[0],"?"),d=l[0],g=l[1],l=l[2],h=f[1],f=f[2];if(0==e.lastIndexOf("?",0))g&&(e=e.replace("?","&")),l+=e;else{if(0==e.lastIndexOf(".",0))if(y(d,"/"))e="index"+e;else{var n=d.lastIndexOf(".");-1<n&&(d=d.substring(0,n))}else y(d,"/")&&0==e.lastIndexOf("/",0)&&(e=e.substring(1));d+=e}d=d+g+l+h+f}e=M(d);d={};d.spfUrl=
e;d.startTime=p();d.fetchStart=d.startTime;g=Pb(a,c.current,null,c.type,!1);g=Qb(g,c.current);d.spfPrefetched=!!g&&"prefetch"==g.type;d.spfCached=!!g;if(g){var c=k(Rb,null,a,c,d,g.key,g.response),r;r=window._spf_state=window._spf_state||{};e=parseInt(r.uid,10)||0;e++;r=r.uid=e;A[r]=c;sa?window.postMessage("spf:"+r,"*"):window.setTimeout(k(pa,null,r),0);return null}g={};if(l=x["request-headers"])for(r in l)h=l[r],g[r]=null==h?"":h;if(c.headers)for(r in c.headers)h=c.headers[r],g[r]=null==h?"":h;null!=
c.c&&(g["X-SPF-Referer"]=c.c);null!=c.current&&(g["X-SPF-Previous"]=c.current);if(r=x["advanced-header-identifier"])g["X-SPF-Request"]=r.replace("__type__",c.type),g.Accept="application/json";r=new Sb;l=k(Tb,null,a,c,d,r);r={headers:g,O:x["request-timeout"],M:k(Ub,null,a,r),u:k(Vb,null,a,c,d,r),L:l,N:l};c.withCredentials&&(r.withCredentials=c.withCredentials);x["advanced-response-type-json"]&&(r.responseType="json");return"POST"==c.method?la("POST",e,c.C,r):la("GET",e,null,r)}
function Rb(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=p();b.type&&0==b.type.lastIndexOf("navigate",0)&&(c.navigationStart=c.startTime,x["cache-unified"]||(ta(d),f=!0));b.i&&"multipart"==e.type&&u(e.parts,function(d){d.timing||(d.timing={});d.timing.spfCached=!!c.spfCached;d.timing.spfPrefetched=!!c.spfPrefetched;b.i(a,d)});Wb(a,b,c,e,f)}function Ub(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.f=-1!=a.toLowerCase().indexOf("multipart")}
function Vb(a,b,c,d,e,f,l){if(d.f){f=d.g+f;var g;try{g=sb(f,!0,l)}catch(h){e.abort();b.h&&b.h(a,h,e);return}b.i&&u(g.w,function(d){d.timing||(d.timing={});d.timing.spfCached=!!c.spfCached;d.timing.spfPrefetched=!!c.spfPrefetched;b.i(a,d)});d.a=d.a.concat(g.w);d.g=g.g}}
function Tb(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if("load"==b.type)for(var l in e.resourceTiming)c[l]=e.resourceTiming[l];else if(window.performance&&window.performance.timing&&(f=window.performance.timing.navigationStart,f+e.resourceTiming.startTime>=c.startTime))for(var g in e.resourceTiming)l=e.resourceTiming[g],void 0!==l&&(y(g,"Start")||y(g,"End")||"startTime"==g)&&(c[g]=f+Math.round(l));"load"!=b.type&&(c.navigationStart=c.startTime);d.a.length&&
(d.g=na(d.g),d.g&&Vb(a,b,c,d,e,"",!0));var h;if("json"==e.responseType){if(!e.response){b.h&&b.h(a,Error("JSON response parsing failed"),e);return}h=tb(w(e.response))}else try{h=sb(e.responseText).w}catch(r){b.h&&b.h(a,r,e);return}if(b.i&&1<h.length)for(d=d.a.length;d<h.length;d++)e=h[d],e.timing||(e.timing={}),e.timing.spfCached=!!c.spfCached,e.timing.spfPrefetched=!!c.spfPrefetched,b.i(a,e);if(1<h.length){var n;u(h,function(a){a.cacheType&&(n=a.cacheType)});h={parts:h,type:"multipart"};n&&(h.cacheType=
n)}else h=1==h.length?h[0]:{};Wb(a,b,c,h,!0)}function Wb(a,b,c,d,e){if(e&&"POST"!=b.method&&(e=Pb(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},l=parseInt(x["cache-lifetime"],10),g=parseInt(x["cache-max"],10);0>=l||0>=g||(g=B(),f={data:f,life:l,time:p(),count:0},wa(f),g[e]=f,setTimeout(ua,1E3))}d.timing=c;b.v&&b.v(a,d)}
function Pb(a,b,c,d,e){a=M(a);var f;x["cache-unified"]?f=a:"navigate-back"==d||"navigate-forward"==d?f="history "+a:"navigate"==d?f=(e?"history ":"prefetch ")+a:"prefetch"==d&&(f=e?"prefetch "+a:"");b&&"url"==c?f+=" previous "+b:b&&"path"==c&&(f+=" previous "+L(b).pathname);return f||""}
function Qb(a,b){var c=[];b&&(c.push(a+" previous "+b),c.push(a+" previous "+L(b).pathname));c.push(a);var d=null;ea(c,function(a){var b;a:{b=B();if(a in b){b=b[a];if(va(b)){wa(b);b=b.data;break a}ta(a)}b=void 0}b&&(d={key:a,response:b.response,type:b.type});return!!b});return d}function Sb(){this.f=!1;this.g="";this.a=[]};function Xb(a){return ja(a,function(a){return ya(a,x["link-class"])})}function Yb(a){return ja(a,function(a){return ya(a,x["nolink-class"])})}function Zb(a,b){return ja(a,function(a){return a.href&&"img"!=a.tagName.toLowerCase()},b)}function $b(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||0<a.button)return null;var b=Xb(a.target);return!b||x["nolink-class"]&&Yb(a.target)?null:(a=Zb(a.target,b))?a.href:null}function ac(a){return L(a).origin!=L(window.location.href).origin?!1:!0}
function bc(){if(!t["nav-init"])return!1;var a=parseInt(t["nav-counter"],10)||0;a++;var b=parseInt(x["navigate-limit"],10),b=isNaN(b)?Infinity:b;if(a>b)return!1;a=parseInt(t["nav-init-time"],10);a--;a=p()-a;b=parseInt(x["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}function cc(a,b){var c=b||window.location.href;if(-1!=a.indexOf("#")){var d=M(a),c=M(c);if(d==c)return!1}return!0}
function dc(a){if(!a.defaultPrevented){var b=$b(a);b&&(b=Oa(b),ac(b)&&bc()&&m("spfclick",{url:b,target:a.target})&&(ec(b,{},new fc),a.preventDefault()))}}function gc(a){var b=$b(a);b&&setTimeout(function(){hc(b)},0)}function ic(){var a;a=t["nav-scroll-position"]||null;var b=t["nav-scroll-url"]||"";a=a&&b==window.location.href?a:null;jc();a&&window.scroll.apply(null,a)}
function kc(a,b){var c=new fc({current:b&&b["spf-current"],history:!0,position:b&&b["spf-position"],c:b&&b["spf-referer"],reverse:!(!b||!b["spf-back"])}),d=x["reload-identifier"];d&&(a=Na(a,[d]));ac(a)?bc()?m("spfhistory",{url:a,referer:c.c,previous:c.current})&&(c.position&&(q("nav-scroll-position",[window.pageXOffset,window.pageYOffset]),q("nav-scroll-url",window.location.href)),ec(a,{},c)):X(a,"1"):X(a,"9")}
function ec(a,b,c){lc();if(cc(a,c.current))if(mc(a,c.c,c.current,b)){q("nav-counter",(parseInt(t["nav-counter"],10)||0)+1);nc(a);var d=M(a),e="preprocess "+M(d),f;for(f in H)e!=f&&0==f.lastIndexOf("preprocess",0)&&Ka(f);d=oc()[d];q("nav-request",d);q("nav-promote",null);q("nav-promote-time",null);d&&4!=d.readyState?(d="preprocess "+M(a),e="promote "+M(a),q("nav-promote",a),q("nav-promote-time",p()),Ka(d),I(e,!0),c.history||pc(a,c.c,k(Y,null,b))):(d=k(Y,null,b),e=k(qc,null,b,c),f=k(rc,null,b,c),x["advanced-navigate-persist-timing"]||
sc(),c.type="navigate",c.history&&(c.type+=c.reverse?"-back":"-forward"),b=Ob(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,current:c.current,c:c.c}),q("nav-request",b),c.history||pc(a,c.c,d))}else X(a,"2");else c.history||pc(a,c.c,k(Y,null,b)),tc(a,c)}function tc(a,b){if(b.position)jc(),window.scroll.apply(null,b.position),b.j=!0;else{var c=z(a,"#");if(c[2]){if(c=document.getElementById(c[2]))jc(),c.scrollIntoView(),b.j=!0}else b.j||(jc(),window.scroll(0,0),b.j=!0)}}
function pc(a,b,c){try{za(null,{"spf-position":[window.pageXOffset,window.pageYOffset]}),M(a,!0)!=window.location.href&&Aa(!1,a,{"spf-referer":b},void 0)}catch(d){lc(),c(a,d)}}function Y(a,b,c,d){q("nav-request",null);uc(b,c,a,void 0,d)&&X(b,"10",c)}function qc(a,b,c,d){if(wc(c,d,a))if(d.reload)X(c,"5");else if(d.redirect)xc(a,d.redirect);else try{V(c,d,b,function(){yc(c,d,a)})}catch(e){Y(a,c,e)}else X(c,"3")}
function rc(a,b,c,d){q("nav-request",null);if(t["nav-promote"]==b.b){var e=d.timing||{};e.navigationStart=t["nav-promote-time"];e.spfPrefetched=!0}var f="multipart"==d.type;if(!f){if(!zc(c,d,a)){X(c,"4");return}if(d.reload){X(c,"5");return}if(d.redirect){xc(a,d.redirect);return}}try{V(c,f?{}:d,b,function(){var e=d.name||"";f&&u(d.parts,function(a){e=a.name||e});ca(e);tc(c,b);Ac(c,d,a)})}catch(l){Y(a,c,l)}}function xc(a,b){try{b+=window.location.hash,za(b,null,!0)}catch(c){lc(),Y(a,b,c)}}
function lc(){var a=t["nav-request"];a&&(a.abort(),q("nav-request",null))}function Z(a,b){var c;a&&(c=Array.prototype.slice.call(arguments),c[0]=a,c=aa.apply(null,c));return!1!==c}
function X(a,b,c){c=c?c.message:"";lc();nc();var d=b;c&&(d+=" Message: "+c);m("spfreload",{url:a,reason:d});var e=window.location.href;x["experimental-remove-history"]&&e==a&&(q("history-ignore-pop",!0),window.history.back());setTimeout(function(){var c=x["reload-identifier"];if(c){var d={};d[c]=encodeURIComponent(b);var c=a,g=z(c,"#"),c=g[0],h=-1!=c.indexOf("?")?"&":"?",n;for(n in d)c+=h+n,d[n]&&(c+="="+d[n]),h="&";a=c+g[1]+g[2]}window.location.href=a;cc(a,e)||window.location.reload()},0)}
function Bc(a,b,c){c.b=c.b||a;if(mc(a,void 0,void 0,b,!0)){var d=k(Cc,null,!1,b,c),e=k(Dc,null,!1,b,c),f=k(Ec,null,!1,b,c);c.type="load";Ob(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,withCredentials:b.withCredentials})}}function hc(a,b){a=Oa(a);Fc(a,b||{},new fc)}
function Fc(a,b,c){c.b=c.b||a;if(mc(a,void 0,void 0,b,!0)){var d=k(Cc,null,!0,b,c),e=k(Dc,null,!0,b,c),f=k(Ec,null,!0,b,c);c.type="prefetch";b=Ob(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,current:c.current});a=M(a);oc()[a]=b}}function Cc(a,b,c,d,e){a&&Gc(d);a&&t["nav-promote"]==c.b?Y(b,d,e):uc(d,e,b,!0)}
function Dc(a,b,c,d,e){if(wc(d,e,b,!0)){if(e.reload){if(!a)return;if(t["nav-promote"]==c.b){X(d,"5");return}}if(e.redirect)Hc(a,b,c,e.redirect);else{if(a){var f=k(qc,null,b,c,d,e),l="promote "+M(c.b);G(l,f);if(t["nav-promote"]==c.b){I(l,!0);return}}(a?Cb:V)(d,e,c,function(){yc(d,e,b,!0)})}}}
function Ec(a,b,c,d,e){var f="multipart"==e.type;if(!f){if(!zc(d,e,b,!0)){X(d,"4");return}if(e.reload){if(!a)return;if(t["nav-promote"]==c.b){X(d,"5");return}}if(e.redirect){Hc(a,b,c,e.redirect);return}}var l="promote "+M(c.b);if(a){Gc(d);if(t["nav-promote"]==c.b){G(l,k(rc,null,b,c,d,e));I(l,!0);return}Ka(l)}l=a?Cb:V;try{l(d,f?{}:e,c,function(){Ac(d,e,b,!0)})}catch(g){Cc(a,b,c,d,g)}}
function Hc(a,b,c,d){a=a?Fc:Bc;var e={};u("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(a){e[a]=b[a]});a(d,e,c)}function uc(a,b,c,d,e){a={url:a,err:b,xhr:e};(c=Z((c||{}).onError,a))&&!d&&(c=m("spferror",a));return c}function mc(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=Z((d||{}).onRequest,a))&&!e&&(d=m("spfrequest",a));return d}function wc(a,b,c,d){a={url:a,part:b};(c=Z((c||{}).onPartProcess,a))&&!d&&(c=m("spfpartprocess",a));return c}
function yc(a,b,c,d){a={url:a,part:b};Z((c||{}).onPartDone,a)&&!d&&m("spfpartdone",a)}function zc(a,b,c,d){a={url:a,response:b};(c=Z((c||{}).onProcess,a))&&!d&&(c=m("spfprocess",a));return c}function Ac(a,b,c,d){a={url:a,response:b};Z((c||{}).onDone,a)&&!d&&m("spfdone",a)}function Gc(a){a=M(a);var b=oc(),c=b[a];c&&c.abort();delete b[a]}function nc(a){var b=oc();a=a&&M(a);for(var c in b)a!=c&&Gc(c)}
var sc,Ic=window.performance&&(window.performance.clearResourceTimings||window.performance.webkitClearResourceTimings||window.performance.mozClearResourceTimings||window.performance.msClearResourceTimings||window.performance.oClearResourceTimings);sc=Ic?k(Ic,window.performance):ba;function oc(){return"nav-prefetches"in t?t["nav-prefetches"]:q("nav-prefetches",{})}function jc(){q("nav-scroll-position",null);q("nav-scroll-url",null)}
function fc(a){a=a||{};this.current=a.history&&a.current?a.current:window.location.href;this.history=!!a.history;this.b=a.b||"";this.position=a.position||null;this.c=void 0!=a.c?a.c:window.location.href;this.reverse=!!a.reverse;this.j=!!a.j;this.type=a.type||""};function Jc(){Xa("js");Xa("css");"complete"==document.readyState&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",Jc,!1):document.detachEvent&&document.detachEvent("onreadystatechange",Jc))}document.addEventListener?document.addEventListener("DOMContentLoaded",Jc,!1):document.attachEvent&&document.attachEvent("onreadystatechange",Jc);Jc();
var Kc={init:function(a){var b=!("function"!=typeof window.history.pushState&&!Ca().contentWindow.history.pushState);a=a||{};for(var c in ha)x[c]=c in a?a[c]:ha[c];for(c in a)c in ha||(x[c]=a[c]);if(b){c=uc;if(!t["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",Ea,!1);q("history-init",!0);q("history-callback",kc);q("history-error-callback",c);q("history-listener",Ea);q("history-url",a);q("history-timestamp",p());var d={"spf-referer":document.referrer};
try{za(a,d)}catch(e){c&&c(a,e)}}!t["nav-init"]&&document.addEventListener&&(q("nav-init",!0),q("nav-init-time",p()),q("nav-counter",0),document.addEventListener("click",dc,!1),q("nav-listener",dc),!x["experimental-prefetch-mousedown"]||"ontouchstart"in window||0<window.navigator.maxTouchPoints||0<window.navigator.msMaxTouchPoints||(document.addEventListener("mousedown",gc,!1),q("nav-mousedown-listener",gc)),document.addEventListener("scroll",ic,!1),q("nav-scroll-listener",ic))}return b},dispose:function(){"undefined"!=
typeof History&&History.prototype.pushState&&(lc(),t["nav-init"]&&(document.removeEventListener&&(document.removeEventListener("click",t["nav-listener"],!1),document.removeEventListener("mousedown",t["nav-mousedown-listener"],!1),document.removeEventListener("scroll",t["nav-scroll-listener"],!1)),q("nav-listener",null),q("nav-mousedown-listener",null),q("nav-scroll-listener",null),q("nav-scroll-position",null),q("nav-scroll-url",null),q("nav-init",!1),q("nav-init-time",null),q("nav-counter",null)),
t["history-init"]&&(window.removeEventListener&&window.removeEventListener("popstate",t["history-listener"],!1),q("history-init",!1),q("history-callback",null),q("history-error-callback",null),q("history-listener",null),q("history-url",null),q("history-timestamp",0)));for(var a in x)delete x[a]},navigate:function(a,b){a&&(a=Oa(a),ac(a)?bc()?ec(a,b||{},new fc):X(a,"1"):X(a,"9"))},load:function(a,b){a=Oa(a);Bc(a,b||{},new fc)},prefetch:hc,process:function(a,b){function c(a,c,d,e){a==c&&b&&b(e)}var d=
window.location.href;if("multipart"==a.type){var e=a.parts,f=e.length-1;u(e,function(a,b){V(d,a,null,k(c,null,b,f))})}else V(d,a,null,k(c,null,0,0))}},Lc={cache:{remove:ta,clear:function(){B({})}},script:{load:fb,get:hb,ready:jb,done:function(a){P[O("js",a)]="";Ra("js")},require:kb,declare:function(a,b){if(a){for(var c in a)U[c]=a[c];if(b)for(c in b)T[c]=b[c]}},path:function(a){q("rsrc-p-js",a)},unload:gb,ignore:function(a,b){a=w(a);var c=O("js",a.sort().join("|"));Ha(c,b)},unrequire:lb,prefetch:ib},
style:{load:pb,get:qb,unload:function(a){Ua("css",a)},path:function(a){q("rsrc-p-css",a)},prefetch:rb}},Mc=this.spf=this.spf||{},Nc;for(Nc in Kc)Mc[Nc]=Kc[Nc];for(var Oc in Lc)for(var Pc in Lc[Oc])Mc[Oc]=Mc[Oc]||{},Mc[Oc][Pc]=Lc[Oc][Pc];m("spfready");})();
